'use strict';
const assert=require('assert/strict');const fs=require('fs');const path=require('path');const vm=require('vm');const {test}=require('node:test');
const src=fs.readFileSync(path.join(__dirname,'../outlineStore.js'),'utf8');
const A={lat:40.0001,lng:-100.0001},B={lat:40.0004,lng:-100.0001};
function ring(g,r=5){const lat=r/111320,lng=r/(111320*Math.cos(g.lat*Math.PI/180));return[[g.lat-lat,g.lng-lng],[g.lat-lat,g.lng+lng],[g.lat+lat,g.lng+lng],[g.lat+lat,g.lng-lng]];}
function boot(seed={}){const storage=new Map(Object.entries(seed));const w={};const ctx={window:w,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},console};vm.runInNewContext(src,ctx);return{S:w.OutlineStore,storage};}
test('adjacent greens in the same old coordinate bucket do not share records',()=>{const{S,storage}=boot();S.saveOsm(A.lat,A.lng,ring(A),0);assert.equal(S.chosenRing(B.lat,B.lng),null,'neighbor must not inherit A outline');S.saveOsm(B.lat,B.lng,ring(B),0);assert.equal(Object.keys(JSON.parse(storage.get(S.KEY))).length,2);assert.equal(S.get(A.lat,A.lng).lat,A.lat);assert.equal(S.get(B.lat,B.lng).lat,B.lat);assert.equal(S.get(B.lat,B.lng).chosen,'osm');});
test('distinct-key neighbor cannot inherit a locked source',()=>{const{S}=boot();const c={lat:40.0002,lng:-100.002},d={lat:40.0008,lng:-100.002};S.useThis(c.lat,c.lng,'auto',ring(c));assert.equal(S.get(d.lat,d.lng),null);S.saveOsm(d.lat,d.lng,ring(d),0);assert.equal(S.get(d.lat,d.lng).chosen,'osm');assert.equal(S.get(c.lat,c.lng).locked,true);});
test('moving the pin within its polygon preserves the same source and lock',()=>{const{S,storage}=boot();S.useThis(A.lat,A.lng,'osm',ring(A,20));const pin={lat:A.lat+10/111320,lng:A.lng};assert.equal(S.get(pin.lat,pin.lng).locked,true);S.saveAuto(pin.lat,pin.lng,ring(A,20),0.8);const rec=S.get(A.lat,A.lng);assert.equal(rec.chosen,'osm');assert.ok(rec.autoRing);assert.equal(Object.keys(JSON.parse(storage.get(S.KEY))).length,1);S.setChosen(pin.lat,pin.lng,'auto');assert.equal(S.get(A.lat,A.lng).chosen,'auto');});
test('legacy v2 records remain available only for their own green',()=>{const old={'40.000,-100.000':{lat:A.lat,lng:A.lng,osmRing:ring(A),chosen:'osm',locked:true}};const{S,storage}=boot({'caddy:greenOutlines:v2':JSON.stringify(old)});assert.equal(S.get(A.lat,A.lng).locked,true);assert.equal(S.get(B.lat,B.lng),null);S.saveOsm(B.lat,B.lng,ring(B),0);assert.equal(S.get(A.lat,A.lng).locked,true);assert.equal(Object.keys(JSON.parse(storage.get(S.KEY))).length,2);});
test('invalid coordinate/ring writes cannot corrupt records',()=>{const{S,storage}=boot();assert.equal(S.saveOsm(NaN,A.lng,ring(A),0),null);assert.equal(S.useThis(A.lat,A.lng,'auto',[[91,1],[92,2],[93,3]]),null);assert.equal(storage.size,0);});
